### ISSUE TITLE
Issue with malheur.py module?

### ISSUE THREAD

**Issue by xme** [CAPESandbox/community#435]
I enabled the reporting module "malheur" and got this error:
```
2024-05-15 07:50:41,703 [Task 35] [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Malheur": Strings must be encoded before hashing
Traceback (most recent call last):
  File "/opt/CAPEv2/utils/../lib/cuckoo/core/plugins.py", line 738, in process
    current.run(self.results)
  File "/opt/CAPEv2/utils/../modules/reporting/malheur.py", line 160, in run
    outputfile = os.path.join(basedir, f"malheur.txt.{hashlib.md5(str(random.random())).hexdigest()}")
TypeError: Strings must be encoded before hashing
```
Any idea how to fix this?

**Comment by doomedraven** [comment]
```
outputfile = os.path.join(basedir, f"malheur.txt.{hashlib.md5(str(random.random())).hexdigest()}")
change to
outputfile = os.path.join(basedir, f"malheur.txt.{hashlib.md5(str(random.random()).encode()).hexdigest()}")
```

but malheur is not maintained module, so it might have a lot of problems + it dead itself

**Comment by xme** [comment]
Tx! Will see if it works, otherwise, let's disable it :-)
